#!/usr/bin/env bash
'''
   This script displays numbers 1 to 20 but displays 4 and then bad luck from China for the 4th iteration
   displays 9 and then bead luck from Japan for the 9th iteration and 17 and then bad luck from Italy for
   the 17th iteration.
'''

a=1

while (( a <= 20 ))
do
        echo "$a"
        case $a in
                4) echo "bad luck from chain" ;;
                9) echo "bad luck from Japan" ;;
                17) echo "bad luck from Italy" ;;
        esac
        (( a++ ))
done
