#!/usr/bin/env bash
'''
    This bash script displays the time for 12hours and 59 minutes
    displays hours from 0 to 12
    displays minutes from 1 to 59 using the while loop
'''

hour=0

while (( hour <= 12 ))
do
        echo "Hour: $hour"
        minutes=1
        while (( minute <= 59 ))
        do
                echo "$minute"
                (( minute++ ))
        done
        (( hour++ ))
done
