#!/usr/bin/env bash
'''
   This displays the content of the current directory in a list format
   where only the part of the name after the first dash is displayed use the for loop
'''

list="$(ls)"
for i in $list;
do
    echo "$i" | cut -d "-" -f2
done
